import { HttpResponse, http } from 'msw'

import type { BillingSummary, PublicPlansPayload } from '@/lib/studioApi'

export const samplePublicPlans: PublicPlansPayload = {
  operating_mode: 'public_paid',
  free_account: {
    id: 'free_account',
    entitlement_plan: 'free',
    label: 'Free',
    summary: 'Use Create with wallet credits on the free account. Studio chat unlocks on paid plans.',
    feature_summary: ['Core image models with wallet credits', 'Studio chat stays locked'],
    price_usd: 0,
    billing_period: null,
    checkout_kind: null,
    recommended: false,
    availability: 'included',
    monthly_credits: 50,
    queue_priority: 'standard',
    share_links: false,
    can_generate: true,
    can_access_chat: false,
  },
  subscriptions: [
    {
      id: 'creator',
      entitlement_plan: 'creator',
      label: 'Creator',
      summary: 'Paid everyday plan for Create, Chat, and recurring monthly credits.',
      feature_summary: ['500 monthly credits', 'Newer image models'],
      price_usd: 12,
      billing_period: 'month',
      checkout_kind: 'creator_monthly',
      recommended: true,
      availability: 'self_serve',
      monthly_credits: 500,
      queue_priority: 'priority',
      share_links: true,
      can_generate: true,
      can_access_chat: true,
    },
    {
      id: 'pro',
      entitlement_plan: 'pro',
      label: 'Pro',
      summary: "Higher limits, premium chat lanes, and access to Studio's newest image models.",
      feature_summary: ['2000 monthly credits', 'Advanced and newest image models'],
      price_usd: 36,
      billing_period: 'month',
      checkout_kind: 'pro_monthly',
      recommended: false,
      availability: 'self_serve',
      monthly_credits: 2000,
      queue_priority: 'premium',
      share_links: true,
      can_generate: true,
      can_access_chat: true,
    },
  ],
  credit_packs: [
    { kind: 'credit_pack_small', label: 'Small pack', credits: 100, price_usd: 5, plan: null },
    { kind: 'credit_pack_large', label: 'Large pack', credits: 500, price_usd: 20, plan: null },
  ],
  wallet: {
    contract: 'public_paid_v1',
    free_account_can_buy_credit_packs: true,
    image_generation_requires_credits_or_included_allowance: true,
    spend_order: 'included_then_wallet',
    free_image_generation_included: true,
  },
  entitlements: {
    free: {
      can_generate: true,
      can_share_links: false,
      can_clean_export: false,
      chat_message_limit: 0,
      max_chat_attachments: 0,
      max_incomplete_generations: 1,
    },
    creator: {
      can_generate: true,
      can_share_links: true,
      can_clean_export: true,
      chat_message_limit: 200,
      max_chat_attachments: 4,
      max_incomplete_generations: 3,
    },
    pro: {
      can_generate: true,
      can_share_links: true,
      can_clean_export: true,
      chat_message_limit: 1000,
      max_chat_attachments: 8,
      max_incomplete_generations: 5,
    },
  },
  usage_caps: {
    verified_account_required_for_generation: false,
    captcha_required_for_sensitive_flows: true,
    free_ai_chat_limited: true,
    free_image_generation_included: true,
    wallet_credit_purchase_allowed: true,
    credit_reserve_required_before_generation: true,
  },
  featured_subscription: 'creator',
}

export const sampleBillingSummary: BillingSummary = {
  plan: {
    id: 'creator',
    label: 'Creator',
    monthly_credits: 500,
    queue_priority: 'priority',
    share_links: true,
    can_generate: true,
    can_access_chat: true,
  },
  subscription_status: 'active',
  entitlements: {
    can_access_chat: true,
    premium_chat: false,
    allowed_chat_modes: ['standard'],
    chat_message_limit: 200,
    max_chat_attachments: 4,
    can_clean_export: true,
    can_share_links: true,
    can_generate: true,
  },
  credits: {
    remaining: 420,
    gross_remaining: 420,
    monthly_remaining: 380,
    monthly_allowance: 500,
    extra_credits: 40,
    reserved_total: 0,
    available_to_spend: 420,
    spend_order: 'included_then_wallet',
    unlimited: false,
  },
  wallet: {
    balance: 40,
    wallet_balance: 40,
    included_monthly_allowance: 500,
    included_monthly_remaining: 380,
    reserved_total: 0,
    available_to_spend: 420,
    spend_order: 'included_then_wallet',
    unlimited: false,
  },
  wallet_balance: 40,
  account_tier: 'creator',
  subscription_tier: 'creator',
  generation_credit_guide: {
    available_to_spend: 420,
    reserved_total: 0,
    unlimited: false,
    lane_highlights: [],
    models: [],
  },
  checkout_options: [
    { kind: 'creator_monthly', label: 'Creator', credits: 500, price_usd: 12, plan: 'creator' },
    { kind: 'pro_monthly', label: 'Pro', credits: 2000, price_usd: 36, plan: 'pro' },
  ],
  recent_activity: [],
}

export const defaultHandlers = [
  http.get('*/v1/public/plans', () => HttpResponse.json(samplePublicPlans)),
  http.get('*/v1/billing/summary', () => HttpResponse.json(sampleBillingSummary)),
  http.get('*/v1/auth/me', () =>
    HttpResponse.json({ error: 'Not authenticated' }, { status: 401 }),
  ),
]
