import io
from pathlib import Path

import pytest
from PIL import Image

from studio_platform.models import (
    GenerationJob,
    IdentityPlan,
    OmniaIdentity,
    PromptSnapshot,
    Project,
    StudioWorkspace,
    SubscriptionStatus,
)
from studio_platform.providers import ProviderRegistry
from studio_platform.service import StudioService
from studio_platform.services.asset_protection import GeneratedAssetProtectionPipeline
from studio_platform.store import StudioStateStore


def _build_png_bytes(color: tuple[int, int, int] = (24, 36, 64)) -> bytes:
    buffer = io.BytesIO()
    Image.new("RGB", (768, 768), color).save(buffer, format="PNG")
    return buffer.getvalue()


@pytest.mark.asyncio
async def test_asset_protection_pipeline_embeds_visible_and_invisible_provenance() -> None:
    pipeline = GeneratedAssetProtectionPipeline(secret="test-secret-0123456789")

    protected = pipeline.protect(
        _build_png_bytes(),
        mime_type="image/png",
        asset_id="asset-1",
        job_id="job-1",
        user_id="user-1",
        username="ali",
    )

    assert protected.delivery_bytes != protected.clean_bytes

    delivery_proof = pipeline.inspect(protected.delivery_bytes)
    clean_proof = pipeline.inspect(protected.clean_bytes)

    assert delivery_proof is not None
    assert clean_proof is not None
    assert delivery_proof["valid"] is True
    assert clean_proof["valid"] is True
    assert delivery_proof["job_id"] == "job-1"
    assert clean_proof["user_id"] == "user-1"
    assert clean_proof["issuer"] == "Generated by OmniaCreata"


@pytest.mark.asyncio
async def test_generated_assets_keep_watermarked_delivery_and_owner_clean_export(tmp_path: Path) -> None:
    store = StudioStateStore(tmp_path / "state.json")
    service = StudioService(store, ProviderRegistry(), tmp_path / "media")
    await service.initialize()

    identity = OmniaIdentity(
        id="user-1",
        email="user@example.com",
        display_name="User One",
        username="userone",
        plan=IdentityPlan.PRO,
        subscription_status=SubscriptionStatus.ACTIVE,
        workspace_id="ws-user-1",
    )
    workspace = StudioWorkspace(id="ws-user-1", identity_id=identity.id, name="User One Studio")
    project = Project(
        id="project-1",
        workspace_id=workspace.id,
        identity_id=identity.id,
        title="Project One",
    )
    await store.mutate(
        lambda state: (
            state.identities.__setitem__(identity.id, identity),
            state.workspaces.__setitem__(workspace.id, workspace),
            state.projects.__setitem__(project.id, project),
        )
    )

    job = GenerationJob(
        id="job-1",
        workspace_id=workspace.id,
        project_id=project.id,
        identity_id=identity.id,
        title="Protected render",
        model="flux-schnell",
        estimated_cost=0.0,
        credit_cost=0,
        output_count=1,
        prompt_snapshot=PromptSnapshot(
            prompt="Luxury portrait with teal lighting",
            negative_prompt="",
            model="flux-schnell",
            workflow="text_to_image",
            width=768,
            height=768,
            steps=24,
            cfg_scale=6.5,
            seed=42,
            aspect_ratio="1:1",
        ),
    )

    asset = await service._create_asset_from_result(
        job=job,
        provider="demo",
        image_bytes=_build_png_bytes(),
        mime_type="image/png",
    )
    await store.mutate(lambda state: state.assets.__setitem__(asset.id, asset))

    delivery_token = service._create_asset_delivery_token(
        asset_id=asset.id,
        variant="content",
        identity_id=identity.id,
        share_token=None,
    )
    delivery = await service.resolve_asset_delivery(asset.id, delivery_token, "content")
    clean = await service.resolve_clean_asset_export(asset.id, identity.id)

    delivery_bytes = delivery.content or delivery.local_path.read_bytes()
    clean_bytes = clean.content or clean.local_path.read_bytes()

    assert delivery_bytes != clean_bytes

    delivery_proof = service.asset_protection.inspect(delivery_bytes)
    clean_proof = service.asset_protection.inspect(clean_bytes)
    assert delivery_proof is not None and delivery_proof["valid"] is True
    assert clean_proof is not None and clean_proof["valid"] is True
    assert asset.metadata["clean_export_available"] is True
    assert asset.metadata["storage_key"] != asset.metadata["clean_storage_key"]


@pytest.mark.asyncio
async def test_clean_export_requires_pro_owner(tmp_path: Path) -> None:
    store = StudioStateStore(tmp_path / "state.json")
    service = StudioService(store, ProviderRegistry(), tmp_path / "media")
    await service.initialize()

    free_identity = OmniaIdentity(
        id="user-free",
        email="free@example.com",
        display_name="Free User",
        username="freeuser",
        plan=IdentityPlan.FREE,
        workspace_id="ws-free",
    )
    other_identity = OmniaIdentity(
        id="user-other",
        email="other@example.com",
        display_name="Other User",
        username="otheruser",
        plan=IdentityPlan.PRO,
        workspace_id="ws-other",
    )
    workspace = StudioWorkspace(id="ws-free", identity_id=free_identity.id, name="Free User Studio")
    project = Project(
        id="project-1",
        workspace_id=workspace.id,
        identity_id=free_identity.id,
        title="Project One",
    )
    await store.mutate(
        lambda state: (
            state.identities.__setitem__(free_identity.id, free_identity),
            state.identities.__setitem__(other_identity.id, other_identity),
            state.workspaces.__setitem__(workspace.id, workspace),
            state.projects.__setitem__(project.id, project),
        )
    )

    job = GenerationJob(
        id="job-1",
        workspace_id=workspace.id,
        project_id=project.id,
        identity_id=free_identity.id,
        title="Protected render",
        model="flux-schnell",
        estimated_cost=0.0,
        credit_cost=0,
        output_count=1,
        prompt_snapshot=PromptSnapshot(
            prompt="Studio portrait",
            negative_prompt="",
            model="flux-schnell",
            workflow="text_to_image",
            width=768,
            height=768,
            steps=24,
            cfg_scale=6.5,
            seed=42,
            aspect_ratio="1:1",
        ),
    )
    asset = await service._create_asset_from_result(
        job=job,
        provider="demo",
        image_bytes=_build_png_bytes((16, 48, 90)),
        mime_type="image/png",
    )
    await store.mutate(lambda state: state.assets.__setitem__(asset.id, asset))

    with pytest.raises(PermissionError, match="requires Premium"):
        await service.resolve_clean_asset_export(asset.id, free_identity.id)

    with pytest.raises(PermissionError, match="asset owner"):
        await service.resolve_clean_asset_export(asset.id, other_identity.id)


@pytest.mark.asyncio
async def test_blocked_assets_cannot_clean_export_even_for_pro_owner(tmp_path: Path) -> None:
    store = StudioStateStore(tmp_path / "state.json")
    service = StudioService(store, ProviderRegistry(), tmp_path / "media")
    await service.initialize()

    identity = OmniaIdentity(
        id="user-1",
        email="user@example.com",
        display_name="User One",
        username="userone",
        plan=IdentityPlan.PRO,
        workspace_id="ws-user-1",
    )
    workspace = StudioWorkspace(id="ws-user-1", identity_id=identity.id, name="User One Studio")
    project = Project(
        id="project-1",
        workspace_id=workspace.id,
        identity_id=identity.id,
        title="Project One",
    )
    await store.mutate(
        lambda state: (
            state.identities.__setitem__(identity.id, identity),
            state.workspaces.__setitem__(workspace.id, workspace),
            state.projects.__setitem__(project.id, project),
        )
    )

    job = GenerationJob(
        id="job-1",
        workspace_id=workspace.id,
        project_id=project.id,
        identity_id=identity.id,
        title="Blocked render",
        model="flux-schnell",
        estimated_cost=0.0,
        credit_cost=0,
        output_count=1,
        prompt_snapshot=PromptSnapshot(
            prompt="Studio portrait with soft light",
            negative_prompt="",
            model="flux-schnell",
            workflow="text_to_image",
            width=768,
            height=768,
            steps=24,
            cfg_scale=6.5,
            seed=42,
            aspect_ratio="1:1",
        ),
    )

    asset = await service._create_asset_from_result(
        job=job,
        provider="demo",
        image_bytes=_build_png_bytes((48, 24, 90)),
        mime_type="image/png",
    )
    asset.metadata["protection_state"] = "blocked"
    asset.metadata["library_state"] = "blocked"
    await store.mutate(lambda state: state.assets.__setitem__(asset.id, asset))

    with pytest.raises(PermissionError, match="blocked assets"):
        await service.resolve_clean_asset_export(asset.id, identity.id)
